namespace TownOfRoles
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetCouple,
        SetAssassin,
        SetTarget,
        SetGATarget,

        VersionHandshake,
                
        SetPhantom,
        PhantomDied,
        CatchPhantom,

        SetAvenger,
        AvengerDied,
        CatchAvenger,

        SetTraitor,
        TraitorSpawn,

        StealerVotes,

        ScavengerWin,
        ScavengerLose,
        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        JesterLose,
        ExecutionerLose,
        AmnesiacLose,
        GlitchLose,
        JuggernautLose,
        ArsonistLose,
        NobodyWins,
        PhantomLose,
        GAImpWin,
        GAImpLose,
        CrewWin,
        ImpWin,
        PlaguebearerWin,
        PlaguebearerLose,
        PestilenceWin,
        PestilenceLose,
        WerewolfWin,
        WerewolfLose,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetExtraVotes,
        SetSwaps,
        Protect,
        AttemptSound,
        Morph,
        Mine,
        Swoop,
        Douse,
        Ignite,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        TimeFreeze,
        AssassinKill,
        RewindRevive,
        LighterOn,
        AvengerFinished,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        GAProtect,
        Silence,
        Infect,
        TurnPestilence,
        Disperse,
        Escape,
        Revive,
        Convert,
        ChameleonSwoop,
        CamouflagerSwoop,
        Imitate,
        StartImitate,
        Detonate,

        BypassKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        AddMayorVoteBank,
        RemoveAllBodies,
        CheckMurder,
        SubmergedFixOxygen,

        SetColor,
        
        SetSpawn,
        SetSpawnAirship,
        DoorSyncToilet,
        SyncPlateform
               
    }
}
