namespace TownOfSushi
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetExtraVotes,
        SetCouple,
        SetAssassin,
        CamouflagerSwoop,        
        SetTarget,
        SetGATarget,
        AddMayorVoteBank,
        SetPhantom,
        CatchPhantom,

        SetAvenger,
        CatchAvenger,

        SetTraitor,
        TraitorSpawn,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        CrewWin,
        NobodyWins,
                PlaguebearerWin,
        PestilenceWin,
        WerewolfWin,
        SurvivorOnlyWin,
        VampireWin,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetSwaps,
        Protect,
        AttemptSound,
        Morph,
        Mine,
        Swoop,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        DoomsayerKill,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        GAProtect,
        Blackmail,
        Infect,
        TurnPestilence,
        Disperse,
        Escape,
        Revive,
        Convert,
        ChameleonSwoop,
        Imitate,
        StartImitate,
        Bite,
        Reveal,
        Prosecute,
        Confess,
        Bless,
        Camouflage,
        InformantCultistReveal,

        BypassKill,
        BypassMultiKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen
    }
}
